#!/bin/bash
score_report="/home/cyber/Desktop/ScoreReport.html"

function check()
{
        if ( eval $1 ); then
                if (cat $score_report | grep $2); then
                        sed -i "$3/$2/$4/g" $score_report
                fi
        elif ( ! eval $1 ); then 
                if (! cat $score_report | "grep $2</p>"); then
                        sed -i "$3/$4/$2/g" $score_report
                fi
        fi
}

while true
do
        #Forensics
        check 'cat /home/cyber/Desktop/Forensics_1 | grep "L0y0l@B3@t$H@ll"' 'vuln1' '19s' 'Forensics 1 Correct'
        check 'cat /home/cyber/Desktop/Forensics_2 | grep "1.22.1-9"' 'vuln2' '20s' 'Forensics 2 Correct'
        check 'cat /home/cyber/Desktop/Forensics_3 | grep "password"' 'vuln3' '21s' 'Forensics 3 Correct'

        #Ngnix
        check 'cat /etc/nginx/nginx.conf | grep "server_token on"' 'vuln4' '22s' 'Disabled Server Tokens'
        check 'cat /etc/nginx/nginx.conf | grep "ssl_protocols" | grep "1.2" | grep "1.3"' 'vuln5' '23s' 'Ngnix uses tls 1.2 and 1.3'
        check '! cat /etc/nginx/nginx.conf | grep "client_body_timeout 0s"' 'vuln6' '24s' 'None 0 client timeout'
        check 'cat /etc/nginx/nginx.conf | grep "allow 192.168.10.0"' 'vuln7' '25s' 'Correct ip whitelist'
        check 'cat /etc/nginx/nginx.conf | grep "deny 188.199.10.0/24"' 'vuln8' '26s' 'Correct ip blacklist'
        check 'cat /etc/nginx/nginx.conf | grep "net.ipv4.conf.all.rp_filter = 1"' 'vuln9' '27s' 'sysctl protection 1'
        check 'cat /etc/nginx/nginx.conf | grep "net.ipv4.tcp_syncookies = 1"' 'vuln10' '28s' 'sysctl protection 2'
        check 'cat /etc/nginx/nginx.conf | grep "user nginx"' 'vuln11' '29s' 'Correct Nginx user'
        check '! cat /etc/nginx/nginx.conf | grep "#pid"' 'vuln12' '30s' 'set pid_file'
        check 'cat /etc/nginx/nginx.conf | grep "error_log /var/log/nginx/error.log"' 'vuln13' '31s' 'correct error logging'
        check 'cat /etc/nginx/sites-available/default | grep "listen 443"' 'vuln14' '32s' 'Nginx set to run on correct port'

        #PostgreSQL
        check 'cat /etc/postgresql/15/main/postgresql.conf | grep "port = 8080"' 'vuln15' '33s' 'Postgres set to run on the correct port'
        check 'cat /etc/postgresql/15/main/postgresql.conf | grep "ssl = on"' 'vuln16' '34s' 'Postgres ssl enabled'
        check '! ls /etc/postgresql/15/main/conf.d | grep "envvars.conf"' 'vuln17' '35s' 'Deleted bad Postgres config file'
        check '! ls /etc/postgresql/15/main/conf.d | grep "ports.conf"' 'vuln18' '36s' 'Deleted bad Postgres config file'
        check '! cat /etc/postgresql/15/main/pg_hba.conf | grep "local" | grep "postgres" | grep "trust"' 'vuln19' '37s' 'Postgres requires authentication'

        #PHP 8.2
        check 'cat /etc/php/8.2/fpm/php.ini | grep "expose_php = Off"' 'vuln20' '38s' 'Expose php turned off'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "short_open_tag = Off"' 'vuln21' '39s' 'PHP short tags turned off'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "asp_tags = Off"' 'vuln22' '40s' 'PHP asp tags turned off'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "implicit_flush = Off"' 'vuln23' '41s' 'PHP implicit flush turned off'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "max_execution_time = 30"' 'vuln24' '42s' 'PHP max execution time set to 30'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "input = 30"' 'vuln25' '43s' 'PHP max input time set to 60'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "log_errors = On"' 'vuln26' '44s' 'PHP logs errors'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "ignore_repeated_errors = Off"' 'vuln27' '45s' 'PHP does not ignore repeated errors'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "report_memleaks = On"' 'vuln28' '46s' 'PHP reports memleaks'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "auto_globals_jit = On"' 'vuln29' '47s' 'PHP globals are deleted after use'
        check 'cat /etc/php/8.2/fpm/php.ini | grep "enable_dl = Of"' 'vuln30' '48s' 'PHP extensions disabled'
        check '! ls /etc/php/8.2/fpm/conf.d | grep "passwords"' 'vuln31' '49s' 'File containing a password removed'

        #Samba
        check 'cat /etc/samba/smb.conf | grep "obey pam restrictions = yes"' 'vuln32' '50s' 'Samba uses pam'
        check '! cat /etc/samba/smb.conf | grep "browseable = yes"' 'vuln33' '51s' 'Samba: browseable set to no'
        check 'cat /etc/samba/smb.conf | grep "map to guest = bad user"' 'vuln34' '52s' 'Correct Samba guest configuration'

        #BaseOS
        check 'ufw status | grep "active"' 'vuln35' '53s' 'Firewall enabled'
        check '! dpkg -l | grep "hydra"' 'vuln36' '54s' 'Hydra removed'
        check '! dpkg -l | grep "hashcat"' 'vuln37' '55s' 'Hashcat removed'
        check 'cat /etc/apt/sources.list | grep "bookworm"' 'vuln38' '56s' 'Correct apt repository'
        check '! cat /var/spool/cron/crontabs/Matthew | grep "nc"' 'vuln39' '57s' 'Netcat backdoor removed'
        check '! cat /etc/group | grep "Ginger"' 'vuln40' '58s' 'Unauthorized user removed'
        check '! ls -a /etc/skel | grep ".back"' 'vuln41' '59s' 'Skel backdoor removed'
done
        
        
        
        
        

